name: demo
on:
  push:
    branches:
      - main
env: 
  region: us-east-1
jobs:
  

  tf-plan:
    permissions: 
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.region }}
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.repository_owner }}-${{ github.actor }}
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: petro
      - uses: alonch/actions-aws-website@main
        with: 
          domain: realsense.ca
          subdomain: actions-aws-website
          path: public
            
      - run: echo "$ACTIONS_AWS_WEBSITE"