name: Deploy Ephemeral Environment
on:
  pull_request:
env: 
  AWS_REGION: us-east-1
  DOMAIN: ${{github.head_ref}}.test.realsense.ca
permissions: 
  id-token: write
jobs:
  # apply:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v4
  #     - uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-region: us-east-1
  #         role-to-assume: ${{ secrets.ROLE_ARN }}
  #         role-session-name: ${{ github.repository_owner }}-${{ github.actor }}
  #     - uses: alonch/actions-aws-backend-setup@main
  #       with: 
  #         instance: demo
  #     - uses: alonch/actions-aws-website@main
  #       id: website
  #       with: 
  #         domain: 
  #         content-path: public
  #         action: plan
  plan:
    # needs: apply
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.repository_owner }}-${{ github.actor }}
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: demo
      - uses: alonch/actions-aws-website@main
        id: website
        with: 
          domain: ${{ env.DOMAIN }}
          action: plan
      
  # destroy:
  #   needs: plan    
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v4
  #     - uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-region: us-east-1
  #         role-to-assume: ${{ secrets.ROLE_ARN }}
  #         role-session-name: ${{ github.repository_owner }}-${{ github.actor }}
  #     - uses: alonch/actions-aws-backend-setup@main
  #       with: 
  #         instance: demo
  #     - uses: alonch/actions-aws-website@main
  #       id: website
  #       with: 
  #         domain: ${{ env.DOMAIN }}
  #         action: destroy