name: demo
on:
  push:
    branches:
      - main
env: 
  AWS_REGION: us-east-1
  DOMAIN: actions-aws-website.realsense.ca
jobs:
  tf-plan:
    permissions: 
      id-token: write
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: "https://${{ env.DOMAIN }}"

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: ${{ github.repository_owner }}-${{ github.actor }}
      - uses: alonch/actions-aws-backend-setup@main
        with: 
          instance: petro
      - uses: alonch/actions-aws-website@main
        id: website
        with: 
          domain: ${{ env.DOMAIN }}
          path: public
          action: apply